### PR TITLE
Offer overlay and justStaticExecutables package

### PR DESCRIPTION
**Pull request by voidus**
I'd prefer to use an overlay to integrate it into my home-manager config.

Feel free to reject this if it doesn't fit your vision. I removed the `developPackage` because I don't think it's needed anymore, but if there are use cases for it that aren't covered we can somehow have both maybe.

### CODE REVIEW

**Comment by gbataille** [comment]
Hey @voidus 

thanks for your contribution. I haven't touched this repo for a while and have not done any Nix ever since :D
Nor did I actually do much at the time.

I'll call a friend ☎️ 

@guibou can you have a look

**Comment by voidus** [comment]
If you want you wait a bit, I'm looking into upgrading it to new dependency versions so it build with recent nixpkgs.

**Comment by voidus** [comment]
I fiddled with the nix stuff some more and actually re-did the fix from your branch, I got a syntax error with the where. This one works for me.

If you'd rather not have the direnv stuff or would prever the nix stuff to be done differently, feel free to let me know or cherry-pick as you like of course.

**Comment by voidus** [comment]
BTW, the daemon is still starting by default, contrary to what the readme says

**Comment by guibou** [comment]
I had a look and it looks great, `nix build`, `nix run` and `nix develop` are fine. The overlay can be used. Everything nix related is fine from my point of view. I have no idea about the haskell part.

**Comment by gbataille** [comment]
Hey @voidus, back from vacation and had a chat with my friend @guibou who is much more knowledgeable than me on nix. I get it and it makes sense. I'm going to merge your 2 PRs.

I'm not going to create a release just yet, I need to take some time to fix my local env first, but it does not matter if you install it from source as I guess you do

Again, it's weird that you have problems with the daemon (there should be a single instance polling only the latest visited git repo). If you have any more details, please feel free to share.

cheers

**Comment by voidus** [comment]
For the record, I'm still planning to look into this but work and life and stuff are keeping me busy =/

**Comment by gbataille** [comment]
Hey @voidus 
no problem at all ;)

**Pull request merged**
