### PR TITLE
Add flake

### PR DESCRIPTION
**Pull request by jlesquembre**

### CODE REVIEW

**Comment by gbataille** [comment]
Hey @jlesquembre thanks for that. I don't know Flake so let me just a second and I'll have a look.

**Comment by gbataille** [comment]
@guibou I don't know if you know this, but if not it'll interest you.

@jlesquembre thanks. Did not know flake and I like it. I have however not touched haskell or nix in a while so I'm a bit hard pressed to understand the structure/syntax but it looks ok and I'll trust you !

I guess I have a question though. I think what I see is that you have put the same nixpkgs version that I used last in the flake file, thus "locking" it there, and possibly allowing it to be upgraded later by the package manager, right?

But then:
- I don't see how it interacts with the nix files already there like `nixpkgs.nix` and `default.nix` where the nixpkgs version is hardcoded for example
- do we need to change something to the build process or is `nix build` just going to take care of it?

Can you just give a 2 lines explainer?

**Comment by guibou** [comment]
@gbataille I know about flake. I love it, but from my point of view it is not ready yet for "production" (We do have many issues at work with it unfortunately). However for a project like gitHUD, that's great. The benefit will be:

- It will be easier for you to upgrade nixpkgs: `nix flake update` and that's done, instead of fighting with changing your `nixpkgs.nix` and setting the correct `sha256`. That's minor, but convenient.
- Outside users will be able to load githud in their flake for free (e.g. `inputs.githud.url = "github/gbataille/gitHUD` and boom, they your project available).

Usages:

- `nix build` will, like `nix-build`, build the result in `./result`:

```
λ narwal githud → λ git df9759f → ./result/bin/githud
githud: githudd: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)
```

(Apparently I don't have a github rc file ;) You may want to improve the error message here).

- `nix develop` will give you a development shell, like what `nix-shell` was used to do.

It does not interact anymore with `nixpkgs.nix` and `default.nix` that you can remove. However, `nix-build` and `nix-shell` are still using the `nixpkgs.nix` and `default.nix` files, and actually, I think that `nix build` is using it too if `flakes` is not activated.

By removing `nixpkgs.nix` and `default.nix`, you force your project to use a "still considered as beta" feature of nix.. You can have a look at `flake-compat` which is a way to rewrite your `default.nix` so it uses `flake.nix` and `flack.lock`.

**Comment by jlesquembre** [comment]
@gbataille sorry for not writing an explanation about flakes, I was in a hurry when I submitted this PR, but I was already using that flake on my system for a couple of days.

To answer your question, `flake.nix` and `nixpkgs.nix` / `default.nix` are independent, the first will be used by the new nix (2.4+) CLI, while the second will be used with older nix versions. @guibou is right, I think we could use `flake-compat` to merge both files and avoid duplicated information. And to my knowledge, `nix build` should continue working the same way. 

 The main reason I wrote that flake is because I'm moving my nix config to the new flake format, and I want to continue using githud. IMO, flakes make easier to install githud (at least for an end user like me). Since githud is broken on nixpkgs, I had this on my nixos configuration: 

```nix
let
  githud = import
    (pkgs.fetchFromGitHub {
      owner = "gbataille";
      repo = "gitHUD";
      rev = "3.2.2";
      sha256 = "1csb3xqkayr73k331id41n9j3wnvb35nyi21bm244yz4a2a9z1i9";
    })
    { };
in
{
  environment.systemPackages = [githud];
}
``` 

while now with flake I can install it like this:

```nix
{
  inputs. githud. url = "github:gbataille/gitHUD";
  outputs = { ... }@inputs:
  # ...
  environment.systemPackages = [
     inputs.githud.defaultPackage."${system}"
   ];
}
```

As you can see, you don't need to maintain the hash manually, you can use `nix flake update` command to take care of that

Also, maybe you already know it, but just in case I recommend this article to get a better understanding about flakes:
https://www.tweag.io/blog/2020-05-25-flakes/

I hope I was able to clarify it a bit. Thanks a lot for writing githud, still quite useful to me after years using it :)

**Comment by gbataille** [comment]
Hey @jlesquembre 

flake looks good and I don't overly care for the back compatibility. Nix here is just a build tool for something that has not changed in a long while. And I don't even remember the basics... it's been too long I haven't used this stack.

It seems like a good idea to me to add this, so thanks for the contribution

**Pull request merged**
