### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by voidus**
This depends on #37  and relaxes version bounds to allow building with nixpkgs unstable, everything still seems to work

### CODE REVIEW

**Comment by gbataille** [comment]
on principle this looks good, but again, I'll ask a friend to have a look with me. I'm too rusty. The only thing I don't want it to change the default. I'll keep the daemon on by default, but I agree that we should be able to disable it, and the option should work.

**Comment by voidus** [comment]
Rebased out the commit that changed the default, but I do want to mention that it's severely broken for me, spawning a large number of githudd processes, and the readme should probably be fixed

**Comment by gbataille** [comment]
@voidus this is weird. supposedly there should be a single background `githudd` daemon. I had a few issues when I introduced it years ago but I have not had problem since. I have a single background process myself, and I have had no other complaints.

If you can track conditions in which several processes are started, I'm interested.

Noted for the README

(also note that I'll soon be on vacation with no computer, so not forgetting you, but might take a bit of time)

**Comment by gbataille** [comment]
thanks for the help @voidus.

**Pull request merged**
